# Generated by Django 2.2.9 on 2020-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
