# Generated by Django 2.2.9 on 2020-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='alternate',
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
