# Generated by Django 2.2.9 on 2020-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product', unique=True),
            preserve_default=False,
        ),
    ]
