# Generated by Django 2.2.9 on 2020-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0002_auto_20200216_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='name',
        ),
        migrations.AddField(
            model_name='catalog',
            name='alternate',
            field=models.BooleanField(default=False),
        ),
    ]
