# Generated by Django 2.2.9 on 2020-02-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0004_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='addyart/static/products/'),
        ),
    ]
