# Generated by Django 2.2.9 on 2020-02-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addyart', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product description...', max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
